### ISSUE TITLE
App is not working with new v6 Mi-light bridge and bulbs

### ISSUE THREAD

**Issue by keevstr** [eladnava/sunriser-android#14]
Hey, i know you haven't worked on this for a while, but i was hoping that you could still help me out. I've been trying to get your app to work on the new v6 mi-light bridge and bulbs i got just so I could set up a sunrise light, but I just can't connect using your app. It works with the standard mi-light app, but that doesn't have a sunrise feature. I used the LimitlessLED windows app to confirm the connection and i tried using the ip and port that the bridge is sitting on, but without success. I'm wondering if the commands have changed? I've tried looking through your code, but i'm having a hard time getting through it, as i'm not that familiar with app dev. I attached a screenshot of the LimitlessLED app that has all the main commands in hex and also some details about the commands that and am hoping that it shows enough info for a quick and easy fix perhaps? I would just love it if I could get your app to work and wake up to a natural sunrise. Thanks

![image](https://user-images.githubusercontent.com/34408871/33814090-1bd04c48-dde5-11e7-9ab6-28d849284c2a.png)

**Comment by eladnava** [comment]
Hi @keevstr,
Unfortunately, all of the command codes have changed in the new MiLight bridge. 

These are actually implemented in a different project I created called `milight-api` that this project depends on:
https://github.com/eladnava/milight-api/tree/master/api/src/main/java/com/eladnava/milight/api/lib

If you would like to take a stab at changing them, please go ahead. I will unfortunately not be able to devote time into adding support for this new router.

**Comment by keevstr** [comment]
This is great. No worries about the time. I figured you'd moved on to other projects or are just busy with life. This link is what I was looking for before. I think i can figure it out with this. Thanks again

**Comment by eladnava** [comment]
Hi @keevstr,
Great to hear that. I wish you the best of luck! 🍺 

If you manage to get it working and wish to share your work, you're more than welcome to submit a PR.
